### ISSUE TITLE
Not getting same/similar results by using your code & database at Frame Prediction Visualizations section

### ISSUE THREAD

**Issue by Marianatorres0752** [keras-team/keras-io#1128] opened 2022-11-03 17:36 UTC
I was training the same database with author'scode but I'm not having the same or similar results at Frame Prediction Visualizations
 section from [https://keras.io/examples/vision/conv_lstm/](https://keras.io/examples/vision/conv_lstm/.) Seems that the images are getting a gray background, I'd love to see if you could support me by mentioning me if I failed in a certain part of implementing author's code :)

Here's my colab : [https://colab.research.google.com/drive/1S8JN9WBwAFaSuuPd28X8697EoYHWHGfN?usp=sharing](https://colab.research.google.com/drive/1S8JN9WBwAFaSuuPd28X8697EoYHWHGfN?usp=sharing)

Thanks for your efforts and all in advance :)

**Comment by sachinprasadhs** [comment] 2024-07-24 22:41
Closing it as duplicate of https://github.com/keras-team/keras-io/issues/732

**Closed by sachinprasadhs** 2024-07-24 22:41 UTC
Labels: type:support
