### ISSUE TITLE
Unable to replicate results of convLSTM

### ISSUE THREAD

**Issue by mulvey-g** [keras-team/keras-io#741] opened 2021-12-14 12:21 UTC
My predicted output results of the moving MNIST are not as good as what is visible on the website. The first predicted image appears to be the most accurate, and after that, the images get very blurry very quickly.  I believe there is someone else who is having a similar difficulty.  

I am using NVIDIA GeForce RTX 2080 with Max-Q design, TensorFlow 2.5.0 and cudNN 8.2.1.
After 20 epochs, these are some of the results I got.  I did not make any alterations to the code

**Results I got**

![convLSTM_20_epochs_27_10_2021 2](https://user-images.githubusercontent.com/56536807/145996800-46c6cad4-5084-40b3-b5c5-63c26efe77fb.jpg)
![convLSTM_20_epochs_exact_code_27_10_2021](https://user-images.githubusercontent.com/56536807/145996823-83d4de2d-745c-4bb7-9ca1-a628ab85a899.jpg)

**Results produced on the Keras website after 20 epochs.**  
![keras example of frame prediction](https://user-images.githubusercontent.com/56536807/145996903-f5f69ed2-813d-4219-bebb-1467985be1c6.jpg)

**Comment by sachinprasadhs** [comment] 2024-07-23 21:12
Duplicate of: https://github.com/keras-team/keras-io/issues/732

**Closed** 2024-07-23 21:12 UTC
Labels: stat:awaiting keras-eng, type:support
