### ISSUE TITLE
neural_machine_translation_with_transformer does not work

### ISSUE THREAD

**Issue by macildevil** [keras-team/keras-io#1239] opened 2023-02-17 14:49 UTC
The code example does not work when simply running it from top to bottom. I have tried on my local setup as well as on 

https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb#scrollTo=A55qzQog07ZZ

The following error is given:

![image](https://user-images.githubusercontent.com/53372135/219686945-fcc43e45-dcd7-42d5-98b2-d518d3d104d1.png)

**Comment by sampathweb** [comment] 2023-02-23 21:32
Thanks for raising the issue.  It looks like a Regression that has happened in TF 2.10 release and might be related to optimizer updates.  Although, changing to Legacy optimizers didn't help resolve the issue.

As a a workaround, you could update the tensorflow to 2.9 (`!pip install tensorflow~=2.9.0`) to run the notebook.  Will follow-up on the issue.

**Comment by sampathweb** [comment] 2023-02-26 00:11
Looking back, found an error on Broadcasting in the example.  Its fixed in PR: #1254.  Please try again and re-open the issue if the problem is still there.

**Closed by sampathweb** 2023-02-26 00:11 UTC
