### ISSUE TITLE
No attribute 'image_dataset_from_directory'

### ISSUE THREAD

**Issue by baksheev** [keras-team/keras-io#12] opened 2020-05-09 14:37 UTC
Hi!
I was going through the [guide](https://keras.io/examples/vision/image_classification_from_scratch/) and I got the error:
`AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'`

Here
https://github.com/keras-team/keras-io/blob/a3bb3dc49b8eb0ebbe8a5d91329f8378eacdd7d4/examples/vision/image_classification_from_scratch.py#L83

I have no idea how to fix it and why it's not working. Can you help me?

Package versions:
- keras 2.3.1
- tensorflow 2.1.0

**Comment by swghosh** [comment] 2020-05-09 18:52
The specific function (tf.keras.preprocessing.image_dataset_from_directory) is not available under TensorFlow v2.1 or v2.2 yet. It is only available with the tf-nightly builds and forms a part of the source code in the master branch. 
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory

For more information about installing nightly builds of TensorFlow, you can refer to https://www.tensorflow.org/install or use
```bash
pip install tf-nightly
```
Thanks.

**Comment by swghosh** [comment] 2020-05-09 18:59
After carefully reviewing the keras.io website yesterday, I could also find other examples and source code that involves function calls and reference to classes only available with tf-nightly (or in the master branch of TensorFlow main repo). As also observed in, https://keras.io/examples/keras_recipes/quasi_svm/ where the tf.keras.layers.experimental.RandomFourierFeatures have been used.

https://github.com/keras-team/keras-io/blob/a3bb3dc49b8eb0ebbe8a5d91329f8378eacdd7d4/examples/keras_recipes/quasi_svm.py#L33
https://github.com/keras-team/keras-io/blob/a3bb3dc49b8eb0ebbe8a5d91329f8378eacdd7d4/examples/keras_recipes/quasi_svm.py#L39-L47

/cc: @fchollet Is the whole documentation hosted at keras.io website designed around tf-nightly as of now?

**Comment by fchollet** [comment] 2020-05-10 00:47
> @fchollet Is the whole documentation hosted at keras.io website designed around tf-nightly as of now?

Yes. These features will be in TF 2.3. Past 2.3 we don't expect that there will be discrepancies between the docs and the latest released API.

**Comment by swghosh** [comment] 2020-05-10 06:36
Thanks for the clarification.

**Closed** 2020-05-11 18:35 UTC

**Comment by bsdis** [comment] 2020-05-15 20:13
When is TF 2.3 expected to be released more or less?

**Comment by swghosh** [comment] 2020-05-15 20:19
TensorFlow 2.2 was just released one and half weeks before. Although, there is no definitive announcement about the exact release date of next release cycle, the TensorFlow community usually releases major version updates like once in 5-6 months.
Meanwhile, most of the code on the keras.io website can be runt using the tf-nightly package as well as many examples can be directly run on TensorFlow 2.2 itself.

If you are experiencing any issues, please try:

```bash
pip install tf-nightly
```

And, you should be up and doing in no time!

**Comment by pranabdas457** [comment] 2020-05-21 14:30
I am also getting the same error. Can anyone help me how to resolve this?

module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'

**Comment by swghosh** [comment] 2020-05-21 23:34
Hi @pranabdas457 

> TensorFlow 2.2 was just released one and half weeks before. Although, there is no definitive announcement about the exact release date of next release cycle, the TensorFlow community usually releases major version updates like once in 5-6 months.
> Meanwhile, most of the code on this repo can be runt using the `tf-nightly` package as well as most examples should be fine when directly runt on TensorFlow 2.2 itself.
> 
> If you are experiencing any issues, please try:
> 
> ```shell
> pip install tf-nightly # nightly builds of the tensorflow master branch released each night
> ```
> 
> And, you should be up and doing in no time!

Please try installing the `tf-nightly` package in case you're trying to use `image_dataset_from_directory` function in your code.

**Comment by lilly-chen** [comment] 2020-06-03 23:21
Hi i was gettin "module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'" so i run the pip install tf-nightly.

but now i am getting a new error message cannot import name 'image_dataset_from_directory' from 'tensorflow.keras.preprocessing.image' (/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow/keras/preprocessing/image/__init__.py)

appreciate any suggestion to fix this! Thanks

**Comment by christian-unoxx** [comment] 2020-06-04 02:37
> Hi i was gettin "module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'" so i run the pip install tf-nightly.
> 
> but now i am getting a new error message cannot import name 'image_dataset_from_directory' from 'tensorflow.keras.preprocessing.image' (/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow/keras/preprocessing/image/**init**.py)
> 
> appreciate any suggestion to fix this! Thanks

I also experienced this the other day. I haven't tried it again since.

**Comment by shilan** [comment] 2020-10-14 12:39
Hi, now that tensorflow 2.3 is released, does image_dataset_from_directory work there?

**Comment by TByte007** [comment] 2020-10-16 12:07
Does that mean that if I use PlaidML there is no chance I can use those functions ?

**Comment by swghosh** [comment] 2020-10-16 12:47
> Does that mean that if I use PlaidML there is no chance I can use those functions ?  

Keras has deprecated support for multi backends for quite some time now. The only option here to try out the every new feature that Keras API offers is to stick to the TensorFlow backend a.k.a. tf.keras. 

Look into transitioning your codebase to tf.keras and TensorFlow 2.0 for all the goodness that comes with Eager execution and high level Deep Learning APIs.

**Comment by TByte007** [comment] 2020-10-16 14:30
I wish I can transition my GPU too ;) So what's the point of Keras and why not just use TF directly ? I think I'm missing some point :(

**Comment by swghosh** [comment] 2020-10-16 14:33
> I wish I can transition my GPU too ;) So what's the point of Keras and why not just use TF directly ? I think I'm missing some point :(

Seems like you're deep learning on an AMD GPU with Plaid ML + Keras! 
And, you're correct TensorFlow 2.0 is tightly coupled with Keras API and hence, using tf.keras from tensorflow_v2 is the current default for Keras!

**Comment by TByte007** [comment] 2020-10-16 14:38
> > I wish I can transition my GPU too ;) So what's the point of Keras and why not just use TF directly ? I think I'm missing some point :(
> 
> Seems like you're deep learning on an AMD GPU with Plaid ML + Keras!
> And, you're correct TensorFlow 2.0 is tightly coupled with Keras API and hence, using tf.keras from tensorflow_v2 is the current default for Keras!
> 
> https://github.com/keras-team/keras

Yes I currently only have AMD GPUs and I wrote GA OpenCL kernel for it it was working fine but I wanted to see what other people are doing and I was sure there are LOT better implementation than mine for machine learning (and better optimized kernels). But everything I find it NVIDIA bound - it;s like NVIDIA is paying developers NOT to use anything else and it's really frustrating and it's making not to want to even see NVIDIA product in my life ;) I can always go by a new GPU but Now i'm pissed at NVIDIA lol.

**Comment by swghosh** [comment] 2020-10-17 00:17
@TByte007 Probably, you should try ROCm TensorFlow which is a community supported TF port delivering implementations so that we can run TF2.x on AMD GPUs.

**Comment by TByte007** [comment] 2020-10-22 18:02
> @TByte007 Probably, you should try ROCm TensorFlow which is a community supported TF port delivering implementations so that we can run TF2.x on AMD GPUs.
> 
> https://github.com/ROCmSoftwarePlatform/tensorflow-upstream

That's what I'm about to try given the chance, the problem is that ROCm is not supported under Windows and I cant fit my AMD cards (or even one card) in the Linux machine I have (well , it's never easy I guess). So far PlaidML-Keras under windows works fine and faster than my implementation but sooner or later I have to switch.

**Comment by chasecockrell** [comment] 2020-12-08 17:12
Its pretty sad that this team can't even provide a working tutorial

**Comment by MustafaAlperenYILDIRIM** [comment] 2021-06-08 13:04
> The specific function (tf.keras.preprocessing.image_dataset_from_directory) is not available under TensorFlow v2.1.x or v2.2.0 yet. It is only available with the `tf-nightly` builds and is existent in the source code of the [master](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras) branch.
> https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory
> 
> For more information about installing nightly builds of TensorFlow, you can refer to https://www.tensorflow.org/install or use
> 
> ```shell
> pip install tf-nightly
> ```
> 
> Thanks.

tf-nightly library fixed the error. Thanks

**Comment by surak** [comment] 2021-10-17 16:14
> > Yes. These features will be in TF 2.3. Past 2.3 we don't expect that there will be discrepancies between the docs and the latest released API.
> The same error is still there in Tensorflow Version 2.4

Can confirm. 
The example in https://www.tensorflow.org/tutorials/load_data/images uses keras.utils, 
and both are missing:
```
>>> tf.__version__
'2.4.1'
>>> import tensorflow.keras.utils
>>> dir(tf.keras.utils)
['CustomObjectScope', 'GeneratorEnqueuer', 'OrderedEnqueuer', 'Progbar', 'Sequence', 'SequenceEnqueuer', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'custom_object_scope', 'deserialize_keras_object', 'get_custom_objects', 'get_file', 'get_registered_name', 'get_registered_object', 'get_source_inputs', 'model_to_dot', 'normalize', 'pack_x_y_sample_weight', 'plot_model', 'register_keras_serializable', 'serialize_keras_object', 'to_categorical', 'unpack_x_y_sample_weight']

>>> import tensorflow.keras.preprocessing
2021-10-17 16:13:03.445692: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> dir(tensorflow.keras.preprocessing)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'image', 'image_dataset_from_directory', 'sequence', 'text', 'text_dataset_from_directory', 'timeseries_dataset_from_array']
```

**Comment by mylee16** [comment] 2021-11-06 07:00
The same issue too in TF2.5.2

`import tensorflow as tf
tf.__version__
'2.5.2'
dir(tf.keras.utils)
['CustomObjectScope', 'GeneratorEnqueuer', 'OrderedEnqueuer', 'Progbar', 'Sequence', 'SequenceEnqueuer', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'custom_object_scope', 'deserialize_keras_object', 'experimental', 'get_custom_objects', 'get_file', 'get_registered_name', 'get_registered_object', 'get_source_inputs', 'model_to_dot', 'normalize', 'pack_x_y_sample_weight', 'plot_model', 'register_keras_serializable', 'serialize_keras_object', 'to_categorical', 'unpack_x_y_sample_weight']
`

**Comment by JMIdeaMaker** [comment] 2022-03-24 18:39
It's March and the problems are still here...

**Comment by pandysong** [comment] 2022-04-24 01:56
Same issue here on mac
>>> tf.__version__
'2.3.0'

>>> dir(tf.keras.utils)
['CustomObjectScope', 'GeneratorEnqueuer', 'HDF5Matrix', 'OrderedEnqueuer', 'Progbar', 'Sequence', 'SequenceEnqueuer', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'convert_all_kernels_in_model', 'custom_object_scope', 'deserialize_keras_object', 'get_custom_objects', 'get_file', 'get_registered_name', 'get_registered_object', 'get_source_inputs', 'model_to_dot', 'multi_gpu_model', 'normalize', 'pack_x_y_sample_weight', 'plot_model', 'register_keras_serializable', 'serialize_keras_object', 'to_categorical', 'unpack_x_y_sample_weight']

**Comment by esraa-abdelmaksoud** [comment] 2022-11-02 00:39
I've got the same problem using the version '2.4.0', but the problem was solved with the following:
```tf.keras.preprocessing.image_dataset_from_directory()```
